name: UltraCosmetics
author: iSach
version: ${project.version}
load: POSTWORLD
main: me.isach.ultracosmetics.Core
softdepend: [LibsDisguises, MidiPlayer, Vault]
commands:
  canelacosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics
